### ISSUE TITLE
Cannot open the link for submitting test labels

### ISSUE THREAD

**Issue by jinxing94** [pouyapez/yago3-tc#1]

**Comment by pouyapez** [comment]
Thank you for your interest in our benchmark. I can get access to the submission link in Safari and Chrome, what is your browser? You can try to submit your result using this link:

https://docs.google.com/forms/d/e/1FAIpQLSeBivIOuDBs4aEQddFIwcUnjmrVz7qqXcliHTzrwGYR_CmRJQ/viewform

Let me know if you faced any other issue.

Cheers,
Pouya.

**Comment by jinxing94** [comment]
Thanks for the reply.  I tried both  Safari and Chrome.  I cannot access the google doc webpage as well. It shows that I do not have the permission.

**Comment by pouyapez** [comment]
I removed the restrictions, can you try again?

**Comment by jinxing94** [comment]
I can open it. Thanks.

**Comment by jinxing94** [comment]
Hi,  I submitted a prediction file with test labels via the google doc.  Could you please evaluate it and give me some feedbacks?

**Comment by jinxing94** [comment]
Did you receive the submission?
